apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: ntfy
spec:
  interval: 2m
  chart:
    spec:
      chart: ntfy
      version: 13.9.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    credentials:
      home-s3:
        name: home-s3
        type: s3
        url: ${S3_URL}
        bucket: ntfy
        encrKey: ${BACKUP_ENCRYPTION_KEY}
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: ntfy.${DOMAIN_0}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: le-prod
          nginx:
            enabled: true
          homepage:
            enabled: true
            name: Ntfy
            description:
              ntfy is a simple HTTP-based pub-sub notification service. It allows
              you to send notifications to your phone or desktop via scripts
              from any computer.
            group: Apps
            icon: https://github.com/binwiederhier/ntfy/blob/main/web/public/static/images/ntfy.png
            widget:
              enabled: false
    persistence:
      webpush:
        enabled: true
        mountPath: "/var/lib/ntfy"
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                TZ: America/Toronto
                NTFY_BASE_URL: "https://{{ ( index .Values.ingress.main.hosts 0 ).host }}"
                NTFY_BEHIND_PROXY: "true"
                NTFY_DATABASE_URL: "{{ .Values.cnpg.main.creds.std }}"
                NTFY_AUTH_DEFAULT_ACCESS: "deny-all"
                NTFY_ENABLE_LOGIN: "true"
                NTFY_REQUIRE_LOGIN: "true"
                ENABLE_ATTACHMENT_CACHE_DIR: true
                NTFY_CACHE_DURATION: "31d"
                NTFY_ATTACHMENT_FILE_SIZE_LIMIT: "1G"
                NTFY_ATTACHMENT_TOTAL_SIZE_LIMIT: "9500M"
                NTFY_ATTACHMENT_EXPIRY_DURATION: "31d"
                NTFY_WEB_PUSH_PUBLIC_KEY: "${NTFY_WEBPUSH_PUBLIC_KEY}"
                NTFY_WEB_PUSH_PRIVATE_KEY: "${NTFY_WEBPUSH_PRIVATE_KEY}"
                NTFY_WEB_PUSH_EMAIL_ADDRESS: "${PERSONAL_EMAIL}"
                NTFY_UPSTREAM_BASE_URL: "https://ntfy.sh"
                NTFY_AUTH_ACCESS: "*:up*:write-only"
                NTFY_LOG_LEVEL: debug
                NTFY_AUTH_USERS: ${NTFY_USERS}
                NTFY_PROXY_TRUSTED_HOSTS: ${PODNET}
                NTFY_MESSAGE_DELAY_LIMIT: 7d
    metrics:
      main:
        enabled: true
    cnpg:
      main:
        enabled: true
        database: ntfy
        user: ntfy
        password: ${NTFY_DB_PASSWORD}
        pgVersion: 16
        mode: standalone # CHANGE TO RECOVERY ON RESTORE
        cluster:
          singleNode: true
        backups:
          enabled: true
          revision: "1"
          credentials: home-s3
        recovery:
          enabled: true
          revision: "1"
          credentials: home-s3
        monitoring:
          enablePodMonitor: true
