apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2eoa+9kZgh62zKz8SptnGS0SPfbGRlJOXddpGVGvqH2qmp9LObiH7s5x/GP4Ap9xO6xyOo2eiBi7JXsDTPoElSv5byIsSL66sVGoA+asstZhxzJmP2EQw2SON8sxwBaTHl2eb707GdKSTaz0uC2rsMWlzT5jeJ8yQSJI33WFe5pV+XMAQISm2og2P7Qq3bIijjd2j3I787MQWIGDYA9IrDBneMHGdXTER1ywZzG9qGUDfjBWiBcv1PAGqZPYS9MU4e08o+A2AdA5psynih1Ll/JIGU+ZHpHHbNE3iaILpj7RkeV/l6hYsE+MbfApsbMj4AGIGje+lwdStmr4POPf4bT9ebz9MSB1eqi46SSPtvOjZRrPuljtqb4ZJ660ts1m,iv:/GDTJdgbFXS83wLKvfYT/NYCg/aS10A1mWoVzCOti8k=,tag:3lsqnCF/WTpq2HLEGf9wOg==,type:str]
    identity.pub: ENC[AES256_GCM,data:v+ZCHEsB/XB5rMMFNMu9fMfCSnLPzva58/dRJEPLhJd8Qdgy0p/gblq2gztFp0His/tT0XTVft9CdkRcA3S7OkAnBJo9ebATl+gWgnu/pku6GWD8NfaHpfBikuBGBMLCtZ0eHbDflUmsjrztfJcATVNoR3TW8PGDWvk66bU02qR5Mqbq+1fCDPnaC1hIwsbumf1ZFS1DGdSAumbo8FekrJQS3BwGpiDx9+n2/9Yc2yOiu1xw+wwELV4+rlJaEBzOjyr3zMpQ9V3B3c9GdA==,iv:tKvXO0I/7HUducfWrA6XRBy+YvKUdqvlD0CXhNuqrh8=,tag:akqbMzAJsHfTkZTUXcOolw==,type:str]
    known_hosts: ENC[AES256_GCM,data:kLocsHJHw1sznN77f1Szbk6eazl+vdvA6IQiMNS5XNeWq9St+Rb2mdY0gBhzdvHCx79bAUCsq97gdfwKi+TdDPyFrH0ozLulTUuJbfUsopTOXLXjl8S9BmZGGPSmQ0NYVPtrKsxN1Oc2sF1e/lt2Q0dTx0Jr1ZYZJU+S0zuzsAR3onCmswle5CABxXjslzzqzW8nrMH4dXYatOKQCluNTf0G2vvhRVJ6IiaD,iv:O/Ercsp+NOFdkuhs4h1RknN2yFL0Q4M17c4ByvgA+bA=,tag:eZJSNnkMUqojye9xUTPdrQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYUV2ckllKzdEdlJENzhn
            dTFSQnFBeE0zYW9GMzBnWFZLdjAxRTBJbm1jClh4NFEwQ0JxRGFncDBvT0E3WkxW
            V3lGM3F5RVA3MjJ3aWV5T214UEpuNlUKLS0tIGhLazZUdHFmZkNrSVlwK3VjWDZi
            ZEp0ZU8zZklsUExHWnBZVXNuL2tLZk0Kbc0xU6QmME8qEyuIFr3q5c2/U0+OXoRR
            sOrQ3b8gCLAnzSusG3gPZt1zRSwm7mkZwps70t7cg64V2CRxBKoiPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T16:39:55Z"
    mac: ENC[AES256_GCM,data:sXvKYdsEHTNwlsYy9E44JEzr5MDxZljTsBRuyqLAka+Wc8+/S7wngpE2/xUNMPQnSBnLZgPb8XHcCqRIo3MDbB2oZvOGT+X2AmSMvxLn3LfvMYkdiqh1/iG5/sAfDXL0nHlgpFsw9PiA75KBx2fMIOjXeG3l3Y22SsiM4ncjZ7g=,iv:j7sS4swRWUMBGTcdotz8ImeXde3HA4maTLxWRwk0yyA=,tag:oySgC93kFOzblRHeRb8epA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
