apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:X0yns0UaTbd6nU0WSG2h6z1jge16ZirYJVhC93sCRQekktWHBVV2D0jhDA5ppbKs/0oxiOV/cwt6g5pgC6FeLvzFUvdeyAItvCypCx5Qz4Epo/9WtqUrUC4kEQvZPTsB2dHrLh8C+axUnMkQHfXKC2yPAtfTFSNJs+9+5jRAIDt7j28xSuj84h1yoDqMNPoiY2FdkDN8iayOtZLMYGID2XDA0C/asB/Z/r96r2d3KS/1cySbqT1IbY0eE/biZebbeMctZqC8sci1y3Bt9EhDPJ8IFMmAYfOyHE7NkQ3StHLLX1/jGIbDU43dR0H999xZya+r5ySpUCwQegFP79QXocfe/UyGG5yg8ewiwSf79Vhbfwlma4mVlL45ZdKRuADD,iv:g54vf2Jsx14cfn9j/E1iAk2b81ismdA1nc5qsD6PfM0=,tag:oY7wasLIEJZqllMQ4745Aw==,type:str]
    identity.pub: ENC[AES256_GCM,data:I4BBQ7nOtkHSwu3fHtvybwcSwmtgKHhibFP0eF80aDjGV9OQcwi+uczZC85yCpK+kBEcKDpQap0dKcRkMbQgbOhFKXIid8telMu+XNWH1GmcdYu7oLj+qLMRk5Ca+317WSUO1V3mFHNAWa6GNsZQIMYqpPVxf/MGJ61cyy0hiK1Geoc/DWhhYCz5lbONcbxKgbdRCoMmrA9PZh7IoDsgoejOYyjEKeZdP+/nQEO4OWuDCGkZX9xIfUQk0RzJonnJLsKKHt/zxLORP5xvIQ==,iv:Jqt8jDZffERp7sUapjcrKo8A3E7kwkFzJ09a9Cvu6Mc=,tag:qHlaqgk3RpnG0Fm9r6SWbg==,type:str]
    known_hosts: ENC[AES256_GCM,data:COilBAhlI5l5a5gXUnhiBj718Z2nv23EM6osfFr5hJeLGg8Jbo36A/d5Wy3rHM36crmByX8eKsdjWAeIxVnKPCJg/g8hSg1wQSHDoZKMF/CNwPB+83S1G50ahIkCbO57ZiXYOKkYyo3Cn8v+vIlhGkbE7uKtpGvw8un/V4pfGnN1Xiue1FTqpgFGp/6dDAzFpfSioiLukWzpxO/yAE5x/DvQRHlDXoNkNVnL,iv:bWR2pdTqJ0oLNDwPhJu6Zl2oE8ztqmmdN0qVn1VRBH8=,tag:z3ILpaW+Nv+sJLdd9FGEvQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4L1kxNnpwdXI3OXlVZzhH
            UEkwWGNqZ1VvZ2RJZGF5QlRGaEw4TnhTSlN3Ckl5WkRnQ2VQTVRUUWhZNWFUd0dD
            cEwzb1FKNC9lUDBIUUhza09JSU9DZE0KLS0tIEJKZUIvc1YxQTNlMFdVUU4wd2Yz
            bUl5TGMzMjdZQXRWNG9qUUFPZGN6MjQK0Fl7CKjCjLdKVoDiEYQMpuuTwrIUHXM0
            n6gFNDgiqLXpAjHouoZ4ldmN9rEG0zkFGedRxBLs1sN0xajUFvQ/wQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-13T15:18:09Z"
    mac: ENC[AES256_GCM,data:axvPwSg+P7hprcyCIBTY8GK5110tVvGohv3PS2nhKARxNo6V49LWtO5BPIHesdm3i6F9V1I82nWt2Wu1HiUWviL11TC0VvT0AaTYaOu/kUthuaKV0NCG0gJhvoRjgpVyklHOmQOJdi9XwIOJ5bqQ6+2QeqBT8GlsqaR3QEgn4uk=,iv:xEFbfbg+BRZ/vorxsX0yYqUgM38R0XXM8Qp5Q+LWzQ0=,tag:Eki8nUV/SEaSo40fMdxQgQ==,type:str]
    shamir_threshold: 3
    version: 3.13.0
