apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:H8aPJ6oJBclM1afSXa7dL90PsJbOYxCKZXygviK2ULVaNY5a5BpbyT9ggPg+GdPhHzJlUACCS8sj/9MX5oLGT2m0F7PNea/P3VRgV713BznRc5stf8cuvrp7U1Qlg8suc3X/oPBDla2p5VffT7AJsUfz5J9eINfbOKnGzlSImBW/pUSKEkPsDQW2ipb/FZp3rMD2TiZaMPHL4y3V0sZRVtOd3kauyLxynEQiQ97AF5Bdl3+eq9gWTxiqaxHeRTh/brqqgDHdxt+MQ8GkBZB7WJRht+NMwBRmpM1NyzdBBcpKcX1U5uY9kWXSWpGYtb3qpwBxRJX18wo44Ye+zoTjRAzJ5EgfP9LdaL5zW3xlOr6cAGJ0ss2+LP2ZlYaMDtI/,iv:l31yA5sbY0XrEoEDy+4PbwcowfmFWJPIkozur8RgsBE=,tag:bigaCWsXv5XJ7dtd8a42Xg==,type:str]
    identity.pub: ENC[AES256_GCM,data:+++VjeZS2BvnsYMRP68W1jKNAJstgvXTjfXgbpkUnWd2yIA7M3xaronnCAO2qeEMuSZbegpUYnlPGQAriULPIblUH0gJkpoDOylTY8CT1Zt7WGwsQSe6xzD7IT1joXHKambVazw8aZGYqluOH7TU/8CQcHvqOU6ktg2ByCLDmP3tF92tKg7/mJKlzfMT/JKvBhlvsnjMNTOft3tALYXG/QsX0ebKty4TDvF9WB348MmpIm9Cf5omVdsluwHApNzJ5J7PJ4/4HNZHbMw3JQ==,iv:KW949SxMhQCoDZPq+uUQsJ3ypaqVKDE1NNVfEOApdY8=,tag:fOHWWQseV8RQqx318RewDA==,type:str]
    known_hosts: ENC[AES256_GCM,data:wpm/SXliRxzV+ig0KHdW7xn+8TPVDZ39X7J63nIAtq8SQO247A7EfIXL3Thz25vjfx9sgyOtXTDrdY+rda6lJQ+jeZFsjSgHIJBP1tPBdf1yjYJE+RB8fdFZX6uP7KwNBZpeSp0YSf0Qzw3k5MqLZmXe+vZwuh9xKrsLjrZeo8k1C9yMn/WAZYJNuYWv8gLhVSAFZ++Tfsc7q086NILBzh0muCaExYw1JwPG,iv:jEZRscqUOOo33L+COpa4KP8psm6lHkC2/RuaOqA9OJ4=,tag:miiDX4fpr9di+mJgpSt0ng==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlM21ERHJMRmxsNGJVNjZW
            YVZacW1XT0NseDhhS0MxTjRibVdIY1dnSjF3Ckl6R0t6d0h3OWtWM3FoblpPbXdr
            TzJSN1A2M1hEd3IydWc3N2tCczlxelkKLS0tIFowdWFCV3lVa2JNQU1LWkI2MkhF
            OFJhYXZtRC9Zd2orNER0blFKSHlrWkUK6OX2L7Ou2fHpLubKZaRVBdWCJ64UKMuB
            VrClyYze6kRu/eVvA3HK6jQOxjR4B2H4A5qMhGsTeeSnwD4pIJNFSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-12T14:34:48Z"
    mac: ENC[AES256_GCM,data:20qpdjKofTZ/RGALgAUCachFQifP5g+2HqEXzG/hOqlK+Lpw3Lwf8ALy3JrvLQIwsO+GAwmCzZLQC/2PSkoCZAsBF7MI5WVYGBifTHQ5h3raGI3FBDcggZOe9nn++ov35H0j17k8iLNI78X5/uDjLDe5SALppq3Ou3an8StTv64=,iv:Gm4YdGy798VVvlp2huSwgQ7sA6DMPPw2tZLU+/FLc00=,tag:5ulliKbQWU+3OgAa8AjeGQ==,type:str]
    shamir_threshold: 3
    version: 3.13.0
