apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vita-save-sync
  namespace: vita-save-sync
spec:
  interval: 2m
  timeout: 20m
  chart:
    spec:
      chart: app-template
      version: 18.16.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: vita-save-sync
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    release_name: vita-save-sync
    global:
      stopAll: false
    image:
      repository: ghcr.io/unveroleone/vita-save-sync-server
      pullPolicy: IfNotPresent
      tag: latest@sha256:820b31adba5795947f2b3072caa04169dea3284b761e5d51c82fa775dc8d769e
    service:
      main:
        enabled: true
        type: LoadBalancer
        ports:
          main:
            enabled: true
            port: 3000
            protocol: http
            targetPort: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: vss.${DOMAIN_0}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: le-prod
          nginx:
            enabled: true
    persistence:
      data:
        enabled: true
        type: nfs
        path: ${NFS_BULK_DATA}/Backups/VitaSaves
        server: ${TRUENAS_IP}
        mountPath: /app/data
    workload:
      main:
        podSpec:
          containers:
            main:
              probes:
                liveness:
                  enabled: true
                  path: "/api/status"
                  port: 3000
                  type: http
                readiness:
                  enabled: true
                  path: "/api/status"
                  port: 3000
                  type: http
                startup:
                  enabled: true
                  path: "/api/status"
                  port: 3000
                  type: http
              env:
                USER_TOKEN: ${VITA_SAVE_SYNC_TOKEN}