apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jan-2
  namespace: mc-jan-2
spec:
  interval: 2m
  timeout: 10m
  chart:
    spec:
      chart: minecraft-java
      version: 35.10.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    TZ: America/Toronto
    global:
      stopAll: true
    mcBackupImage:
      repository: docker.io/itzg/mc-backup
      tag: 2026.4.1@sha256:37d21862cbd8a5d2d96667c70b447ba981c956f5d9dc3fd9e7d704cf9ffc589a
      pullPolicy: Always
    credentials:
      home-s3:
        name: home-s3
        type: s3
        url: ${S3_URL}
        bucket: jan-2
        encrKey: ${BACKUP_ENCRYPTION_KEY}
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          mc-router.itzg.me/externalServerName: "jan-2.${DOMAIN_0}"
      rcon:
        enabled: true
        type: LoadBalancer
    persistence:
      data:
        targetSelector:
          main:
            main:
              mountPath: /data
            mcbackup:
              mountPath: /data
              readOnly: true
        volsync:
          - credentials: home-s3
            name: home-s3
            type: restic
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 25 5 * * *
      backups:
        enabled: true
        type: nfs
        path: ${NFS_BULK_DATA}/Backups/Minecraft/jan-2
        server: ${TRUENAS_IP}
        targetSelector:
          main:
            mcbackup:
              mountPath: /backups
    mcbackup:
      zstd_params:
        - --long=25
        - --single-thread
      excludes:
        - "*.jar"
        - "cache"
        - "logs"
        - "*.tmp"
    workload:
      main:
        podSpec:
          containers:
            main:
              imageSelector: j17Image
              env:
                OPS: SunnyEar4432867,Hydranoid620
                WHITELIST: Hydranoid620,SunnyEar4432867
                ENABLE_COMMAND_BLOCK: true
                FABRIC_LOADER_VERSION: 0.14.21
                FORCE_REDOWNLOAD: "false"
                MAX_PLAYERS: 2
                MEMORY: "4G"
                MOTD: <3
                PVP: true
                RCON_PASSWORD: ${MC_RCON_PASSWORD}
                SEED: "-2750416327677348285"
                TYPE: FABRIC
                USE_AIKAR_FLAGS: true
                USE_SIMD_FLAGS: true
                USE_FLARE_FLAGS: false
                VERSION: 1.19.2
                ALLOW_FLIGHT: true
                STOP_SERVER_ANNOUNCE_DELAY: 15
                STOP_DURATION: 40
            mcbackup:
              enabled: true
              imageSelector: mcBackupImage
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false
              env:
                BACKUP_METHOD: "tar"
                DEST_DIR: "{{.Values.persistence.backups.targetSelector.main.mcbackup.mountPath }}"
                SRC_DIR: "{{.Values.persistence.data.mountPath }}"
                SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
                RCON_HOST: '{{ printf "%s-rcon" (include "tc.v1.common.lib.chart.names.fullname" $) }}'
                RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
                RCON_PASSWORD: "{{ .Values.workload.main.podSpec.containers.main.env.RCON_PASSWORD }}"
                SERVER_HOST: '{{ include "tc.v1.common.lib.chart.names.fullname" $ }}'
                ZSTD_PARAMETERS: '{{ join " " .Values.mcbackup.zstd_params }}'
                EXCLUDES: '{{ join "," .Values.mcbackup.excludes }}'
                BACKUP_INTERVAL: "4h"
                INITIAL_DELAY: "2m"
                LINK_LATEST: "false"
                PAUSE_IF_NO_PLAYERS: "true"
                PLAYERS_ONLINE_CHECK_INTERVAL: "1m"
                PRUNE_BACKUPS_DAYS: "4"
                TAR_COMPRESS_METHOD: "zstd"
    resources:
      limits:
        cpu: 4000m
        memory: 6Gi
