apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:0/dISYL1BaHe0j2cUo/iW7BxdRA=,iv:kT7EzD8z+f5ekZhIheUR6ZK6EMvzIs8hMIVwYGPoRBY=,tag:HZHpLk1VuXLGd/4zS0lhMQ==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:dgutrEfqF7FLYKZM1GbJHOoynQO49dE0,iv:099p10WJPOslrHWRKQNdIdfYTRPgcbNkeica19YGgXs=,tag:sa0n4U6d+Auyb/HnasTyJQ==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:CnnDfSmflxgO3hMjRfW5kw8Y2ZJNJ6xq,iv:40gUidWLxieVP0ezH39Aamovks+Dnj6y22gCdEhZIas=,tag:fovtNheD4wFcy+jo4MD43Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NnJmU08veXVMMFNCUEtZ
            c0dXOUxEaENWUUpIaTUrZXBudGozSGZyZUUwCmtYdERRSmZPMFcyQ21kY2gvVUdZ
            TUY3bFdFWDQwZGRtdjF5T1VtdHVheWcKLS0tIGxQMytHTm1NdlArV0FVUDRnM0U1
            SUNxclpKeW9xeXlUeTRMZmdENDY4NUUKC8GhMShZTeRJkNYgDgtR2nRBdvYNNA5E
            xvEqtnMKpoHqSdUOlTpzxmDfjBugjykscaNnZeN1dvh/HrqWlik7FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T17:08:01Z"
    mac: ENC[AES256_GCM,data:crCcCFykqfGqzk77HbiTl/LryTeVJ2xsGW4P8reZZIjcJfp17dPD/V0wcZcD9ucnZZ7f27XR2epmr8aS4/5waMO1IV62UVL1o/moBLaFMJhcub3qD1i7Y7cwbxEhsTBfDIzlO4b16VGCdRY1XfHATneidFbWQ3D8kVf/dhlSzNU=,iv:N3dwb/Q+k3k2ObBkDAJb95BnK8fSNnc8SvkbFu6s4Ds=,tag:MRupcGScQGlf8/G6V8I+WQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
