apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:SlzSFt1DImtc0G2an+Rz+4mq+u8=,iv:z4EpjZUBL8OQpuQ0ZbWBXVazZihtmRpvRkMU7X8euEY=,tag:cV9Kr6BbY/6zxbAA1IVd2w==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:UWWiPpfu8jYinpoXOmFPTGkwObwgj6so,iv:AoH3+LBRGgZkmgpCR6ASg2u5Cj+ibhJ7R+R5w6NCaD4=,tag:AlCPHNyqStyOfrN7Z/vylw==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:9e278dewIKAVIAGmYPksL7IukLITgP3J,iv:7bO2Fja9iSRceg7/x0EqTlfeW0DeYnGTIPZtvRVdauI=,tag:WHYcG3ccblh6ehh8aikL4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVlZyaGJySnFyRVpUSHlS
            dkJjTnAyeFM4VEN2ZCtUUHVTb0lBWUVhb0JBCjNWOHZWcmhPMGJTelRVRjF6RTNM
            Z0VIRzdLSDIyNXhuUy9NaHZ3SHFyajQKLS0tIE8yRTZ2ZDlVYkJUWUZZOVB6TkpT
            QVRiQnhPOFpzYk5BUkxvbk5GS2g1cnMKOHG3P3vavpnNqRbZ2qL+nbXizB2U+Aza
            Ya8y2f4xmeade+WibU60AsCtSqGCyxyzcBlV2oYb/LSa6PTERe9aBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-04T00:07:59Z"
    mac: ENC[AES256_GCM,data:7JlQ+iAPZ0NZEO0RtVtWXKPb+6qZXVxSlJmbo36HN2wb6RN3dSV2cewseHcE6r+SElHsBc7dbhxYyRv0XUgYwOJtVcETBoimB8NoZ8A+meEGXcbTlfNP+H4Zq8fnqJDgb3TY6qh3d6wMPRCPw+DIAh2oaTssnobA2/iVbsJBC74=,iv:8LcP4Krh+lgccOo0RGmrKOKE9MCCk6rAuSGkKlTElDI=,tag:JW5QqZQJbLQGiDfXh38edw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
