apiVersion: v1
kind: Secret
metadata:
    name: testsecret2
    namespace: testing
type: Opaque
data:
    SOMEKEY: ENC[AES256_GCM,data:CgSX+MEsF0JmgG5jJsiKocUJ8Ow=,iv:ANi94Aamxeh0Qz3Aqa6mu+Yebh+TzcHHoKA3Wh5DwrQ=,tag:6E+IHzk36DVNuIrAc9A8Gg==,type:str]
    SOMEKEY2: ENC[AES256_GCM,data:LbfkPoMQocwzrcbF7Qw3i/0HRPlybhpc,iv:tejryBCuzsciP7rqGH55pQVBuQ0XkNR07zrkC1hbwBA=,tag:K+MgU6hPBka0LPbxCm1ocw==,type:str]
    SOMEKEY3: ENC[AES256_GCM,data:6RhPf2RqLK4cizE3K0C6ys9w3QU15XE3,iv:GkXiLxWD/ARhoRys8VeGaucXDM5sGcE5tnTJ6/U0Pw4=,tag:DgDVwEsANXgWhnAVmqX4tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySHE5clVnQlZiZ0t4czVh
            S3BxV1ZTSE5LL05YNVdEUUJvdDBLWWRKNGo4Ckd4NXJKTmMwdTdTMy9hUEMvcm85
            bjNhdk9Yc3JLTitBMnZyelJpQ0RkemcKLS0tIHdHa2pwOGxlVk1TQTBnRmpCTGxl
            MTFaUllqQldOeDg3R2lOYjJEQVNkeGcKqdz28HzGbrXFsRxZVBJcqIkmdexW8bJG
            vVZMq58O2tWlLs/WkiO7VLWe6mKEzluTvY+/ezvgdHYAT9bo3A7rNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-18T14:10:35Z"
    mac: ENC[AES256_GCM,data:Mk/5LzLFn9TyHwg1Vs+SQddRd+XhSqTiS/lFxb1f+jLoImnW3bOyfYip1AfVyxZnbPBJ9AwR0cYqfFlMQxE9bj7ucPZdoe/7HDUJ/y34qj9lSZcUabinZdhpESYfan/hmhqbID3x1NAnNVExhBAfuOz0Vj+z7fa8xryquSu85IA=,iv:+/3U3FSHJOIZSPnXrvgv6D5SA2GiyeSMoFgQ1yGXKDo=,tag:irAQtmO2LKZFZaM64SOi0A==,type:str]
    shamir_threshold: 3
    version: 3.13.1
