apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
  namespace: renovate-operator
spec:
  interval: 2m
  chart:
    spec:
      chart: renovate-operator
      version: 4.10.1
      sourceRef:
        kind: HelmRepository
        name: mogenius
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        cert-manager.io/private-key-rotation-policy: Always
        # Adds auth
        nginx.ingress.kubernetes.io/auth-method: "GET"
        nginx.ingress.kubernetes.io/auth-url: "http://${AUTHELIA_INTERNAL_DNS}/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.${DOMAIN_0}?rm=$request_method"
        nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Name,Remote-Groups,Remote-Email"
      ingressClassName: external
      hosts:
        - host: renovate.${DOMAIN_0}
          paths:
            - pathType: Prefix
              path: /
      tls:
        - secretName: renovate-operator-tls-0
          hosts:
            - renovate.${DOMAIN_0}
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      dashboard:
        enabled: true
