apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  # - renovatejob.yaml
  - renovate-github.secret.yaml
  - renovate-webhook-token.secret.yaml
