kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: renovate-secret
    namespace: renovate-operator
data:
    GITHUB_COM_USER: ENC[AES256_GCM,data:DoCTXR7Wl6tYCdec,iv:VESs5oUcLsoc/Ljcg/9X69JzVS9NImzO5BVf93j6n7Q=,tag:dHNrVH9wa+ZnK1TT8vIWGw==,type:str]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:efhrKzLyuhc1ZXMb0iVpAfLbcE35ZZQjIIrJ+e2odQb7d5ueqfxPFoaka8jKnkeEb9X2x6lbyqvHl23Kg9bkxBbe1802+an1hZM+raA8p+JkW7X6c6gluJYIzfjZdrnlcVAf182kC8bePe3YfRn7eMM6Nouqh/3waO16kw==,iv:3ATR1eRMX4gG5Ps/od86vIP+ON2Hr684+YhHHFhij9w=,tag:OEv7WPTId1oObwUrplQH2Q==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:DQLE6hKLrBIwJ1+icxj/GWXHgjNLRHD5cM4Le7aOO8eXThfrSOJbFmflzVWWK5mxeslsJAom/JqXoW8UqViGr60Wzouo3oNHoALNzXkniOlwQJx0TuVt9UrySG5MZaF/8wazO3PpAzZTlM8nMxf4WMvx3mQzBqAYNN8/kQ==,iv:wdKc4TZzO6YrdFK4hHxqALRhXKkChp0lpXQmmNBzW1g=,tag:P+5gIXOBYj2fP40Epo1yVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWmgyb1JvMWQ0L3hUeXl4
            RzNYM3hWUjZvNE1USEd6ZTRWSnI3UGgvMzJFCmIvQkczM01yU0pNZVpncmdHYnY1
            a1ZYb2pySjdzSldzQzRBdGdqUU5tVWcKLS0tIHRoT3UzZTI3citFdElYMUpDL0Vq
            dEFpdVgwd2w0Z1VBUmUzajNjcWFkUUkKnTANQZbpt9Abt8KWYYXGF/a43r+JiRTU
            qe2+F7cQj4RQo4SXQWwZpT1NQNtJNmnb7pOrsHWSgTQztD4h8rqFYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-12T16:09:28Z"
    mac: ENC[AES256_GCM,data:M8RTQ/ZfntXmnXk+ui3smDmU47x/b2KPIsuiiyOAvePKvUKfA+mm/hJkU/yJZ76MIRUmuFzOeApnC01ZM8NXc66gwyDv3YWIhyBQqx0uf/7oSHFbQAdHS4GjNShuUEP2sMMkFBZ+qg4Hi2JJ60C0QZ5n8fuqd23LkOH3Hnv8msA=,iv:5UVosAIenZ0tP2ILNjf1T4yPLYX2x4zxFiIzu6W+IX0=,tag:N8HHG+9wnzmU1fHrtmoyyg==,type:str]
    shamir_threshold: 3
    version: 3.13.0
