kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: renovate-secret
    namespace: renovate-operator
data:
    GITHUB_COM_USER: ENC[AES256_GCM,data:uucJ5KAGZ/phECc7,iv:yp/4amxpOMFPHo44sDpQZyaOK4FpgQnrNSH8gYNFqFk=,tag:OiOL3wfmMHWfoTs72sMzJQ==,type:str]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:YFeDMZ64FkPCIbmfd6WjYNQAHmOp6jFh1xmE4qiv4tniYUoI3oISi86nZAi9r1lDtD75/7QvyNrqh/iBVs+aOT1YDi1q0UylyGFGNA12+J0/BkWjG0Ea7UiSyfhzDiuGkc/zXOQ9Xt5CDa6xo3E5DLhVtu7ighKzysc3ag==,iv:T9bSFksvCpzXxiz1keDvy0MNGPuj4ovCX/56KhQMZRA=,tag:hwniBKFupZHUENhCM3eY4Q==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:hXNWsdInp7GMXVJl1vvO0kiePFX1OaO1OE2ZcxYgFSjSsG9oyBShXsD+HEp/E48EqJedLiiU1H5T27zQ4nDT/nliC77WBxX/2U4PKllapsB3DzugqdU1egWmIjWk5NIWDAaU7vSk/jhdxy5C5azHKi3Ozbec5Sj8VSwBVA==,iv:Sr6HuSTC99GMQJsfapCLpFf3URuA0wy8jrDcWV55LmQ=,tag:pDtnkOM5QnP+YlYXJLo4Yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUStKWGZ1ZFgyZGZ3ZFhi
            ZnZWdGUyVW4vMDQ2Vkl6QUo5cFF3c2UzckJFCmZVaE9LbWZPQWxDZnJkbUtpOVhM
            bEIwNGI1NERUNzJBenNRS3N5VVdYdU0KLS0tIHVlWmwwK1IrM09vM2ZLd2E5V3VV
            Vk1HMzFDOWwzNnYxOC90UDBZM2cvaFkKisRrruEbkSvzf/tlph8ObcEyhUYIkdn9
            fq908HmcowPokFQEymPX6gaHQgjway6YvqtPc8PSOJ65Y+7zjLxhJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-12T16:14:24Z"
    mac: ENC[AES256_GCM,data:6aQZ/x+Udc+BhisbEDE65PnpLul5di9FHqg0AFUH/E5ckYJ96GeRitcq3Xz7KfxbCPCXZm5Dk0oJid0FiEvlNInV6vCTucxTKoWQtlJmCqp30Z5mE/3YeQLrHR6qwxiSIjzzETenDlCgY0JMHK/0sSxnGVuVHPj6aQCgGurGU50=,iv:GoupdgOrIb4IFiJnwim32CCmRWBNdp97n8HrdkpoE5U=,tag:gj+X6WkIcBF63VNxpzks7Q==,type:str]
    shamir_threshold: 3
    version: 3.13.0
