kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: renovate-github-secret
    namespace: renovate-operator
stringData:
    token: ENC[AES256_GCM,data:QM3tP4KQokNORPPn8JrgRyTBXoqHjRpYjH0QTXVzf9dBOYnjj3UutNEph4AJHWAn8zd5BRUBHHakhL22783E5Q==,iv:0myQPScuZLq87LPoRhHlkEUPlsGA7IZ6B78qZZ+fhw0=,tag:nwRgjNjI5YDhn+YPqTrigA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZHNmaFNielR5QWoreGZH
            MGVRRGtVc2VONjAzZVJZSTBNa0NUcTg2MzEwClhBaFBrWVI5aEU1ZVVyYUVzMDRp
            ZzBsRUlReHVqWnhscUFLbldFWUVCSUEKLS0tIDRwTjRTdnduanBLTG8xYmFuUzhB
            WmpmVGNLejg3Z3FoY3U0a2JHckJHLzgKd8hBRDt7RTSe33ttlQ52MDu71O2IG8VL
            ffRtuTGtEaZdUUB3Cz3wGqvThSSO+3U3JzSdDHWEnId43ZhIT1Lg8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-12T16:42:19Z"
    mac: ENC[AES256_GCM,data:IbBxCm6yz/0grogZeV+IjC9yD/t0zblel6FLvf81i0HTDQGaFd1doiDWGZnREMRrtnBzPKOlG9iOuB7W4i/tWf+M7A7VfhzlprXqRoLKTKmr7YkL1b+aPV1kOLRJmM+XmLqQDCfG3XdIpJUhw7ccfqPsqJZhzFUSwAnaVM63oNg=,iv:c24yetZeARFJpUj2s9gZIoje4O1hmebnk2Q8jaXGPaQ=,tag:yXU6YClxsQD85+uQCZ7Unw==,type:str]
    shamir_threshold: 3
    version: 3.13.0
