kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: renovate-secret
    namespace: renovate-operator
data:
    GITHUB_COM_USER: ENC[AES256_GCM,data:Tsl921Tz1aW9pW4K,iv:o113zB/tiBJoIwIU4M1w7oHRl6hIOOjEaHwioBXVew8=,tag:FICJuoHb1SYiGOV2k8B53Q==,type:str]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:fJsqCJ92ZsA4B3p+CGBuZmcAbnP0K0bur0Tp/d4hBRhuN+VBjH4eWgRFRd2ePTr4wYemTCnsKOYAreoS+Tndp9sLxHWRoz4zLCj5v11Sgxs2QNxO8k7xNCQ7psOThLsZ74YYPD6gHJd/2hE2Ysq9nEZ1p1hdn1xPFYj4dQ==,iv:fXVAPXlkXkEngr6jPRjRdkwbCj8FbmP2mtTMFsw8nfk=,tag:Dx+pwwUpF3or4d5Meh+bTA==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:nrtdvM4y3a1G7EsnCYN4EWw4QhEQu1hDoLkaCsC1ZO/dvF1aVSaWJHrqzsIw4g1MsuOcPj48ff+a6m1CyDnMGWHUMKBxzmpD1GNNOaMi+c5hr56afFvaFyY8/xWHM4J/Z/9s2TDCx0lUSXkXAsJdVP4AgnHuvae3vvl9Cg==,iv:Hz/IKdWRlKuQsUq2KEDoE5sOIHaVr3O6L2DTE6aD9CY=,tag:XjcsDpCyVbjsUhedCKTxLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUXhZS0t5ZDN4Ykw4NjI3
            cE5RamFPdnpWSXNBUG9ZakZoVTBMbU9yWEVvClhiK3dXb0N1VS9OUyt0R3haUktF
            blJtYTZZNDdTbVg0S3JIN2dvUEh2bTAKLS0tIHZTbVdCVkpteVVhaDhZb3hkNHpL
            aXZCSkJnZjIwUU5tMzUrWXBueXE3Rm8KwI2XVAep7b7U3QOTLp+g6u9zy8qTEKKV
            xiSH31rh2DfbEIzDlU8ljzCB7RSjXfoavjilC5rgD3OzkTRL7sRO+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyf88uzyr9gf5jr5z0l2x735cvm6dtkxatw5g37ssurrt3gwn9mqdxnz7z
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-12T16:02:20Z"
    mac: ENC[AES256_GCM,data:8zyRBqHHCPeuO7PO726592lqQBm4VWApxYzqWIJSft4l2BzZJrH0d5fzShOWmn94kdbQyCXshBQnaHk7RldQ48GpVJvwsxqCV3jA34Y9LMr7ZwZ+i3ZxXWT8LLJUK5E+zjWfM3jVvVxvUjoadC5dwXfgg8x4mvyQZRWFSiEd58c=,iv:Tl7Io6hkzk/8sh0bfAq0znrgp6VkKE0y1tE99ryvpdU=,tag:MQgfjIB/Z/qrOjEZN3/HdA==,type:str]
    shamir_threshold: 3
    version: 3.13.0
