apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-talos
  namespace: renovate-operator
spec:
  discoveryFilters:
    - "n-rosati/talos"
  provider:
    name: github
  extraEnv: []
  image: renovate/renovate:43.104.1
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0/15 * * * *
  githubAppReference:
    secretName: renovate-github-secret
    appIdSecretKey: appId
    installationIdSecretKey: installationId
    pemSecretKey: pem
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-github-secret
        key: webhookToken
